### ISSUE TITLE
$host is hardcoded when it should be using CS_HOST

### ISSUE THREAD

**Issue by j-r-t** [wp-premium/gravityformscampaignmonitor#1]
for example

https://github.com/wp-premium/gravityformscampaignmonitor/blob/master/api/class/base_classes.php#L137

https://github.com/wp-premium/gravityformscampaignmonitor/blob/master/api/csrest_administrators.php#L44

Any chance this could get fixed?

**Comment by remcotolsma** [comment]
> Gravity Forms Campaign Monitor Add-On, Git-ified. Synced manual! This repository is just a mirror of the Gravity Forms Campaign Monitor Add-On plugin. Please do not send pull requests and issues.
